const encuentrosCards = [
    "criatura_errante_(1).png",
    "criatura_errante_(2).png",
    "criatura_errante_(3).png",
    "criatura_especial_(1).png",
    "criatura_especial_(2).png",
    "criatura_especial_(3).png",
    "enemigos_(1).png",
    "enemigos_(2).png",
    "enemigos_(3).png",
    "enemigos_(4).png",
];

const obstaculosCards = [
    "acertijo_(1).png",
    "acertijo_(2).png",
    "alarma.png",
    "bloque_de_piedra.png",
    "bola_de_fuego.png",
    "canticos_terrorificos.png",
    "cepo.png",
    "cofre_blindado.png",
    "dardo_evnenenado.png",
    "descarga_electrica.png",
    "despiste.png",
    "desprendimiento.png",
    "destruccion_de_la_mente.png",
    "escombros.png",
    "estaca.png",
    "explosion_magica.png",
    "foso_(1).png",
    "foso_(2).png",
    "foso_(3).png",
    "fuego_cruzado.png",
    "gas_venenoso.png",
    "grieta_profunda.png",
    "guillotina.png",
    "llamaradas.png",
    "muro_de_fuego.png",
    "muro_de_hielo.png",
    "muro_de_piedra.png",
    "oscuridad_total.png",
    "paredes_que_se_cierran.png",
    "penumbra_(1).png",
    "penumbra_(2).png",
    "puerta_blindada.png",
    "puerta_cerrada_con_llave_(1).png",
    "puerta_cerrada_con_llave_(2).png",
    "puerta_cerrada_con_llave_(3).png",
    "rastrillo.png",
    "rastrillo_que_se_precipita.png",
    "roca_rodante.png",
    "vigia_atento.png",
    "zona_inundada.png",
];

const poderCards = [
    "arma_envenenada.png",
    "aturdir.png",
    "berserker.png",
    "crece_la_reserva.png",
    "criatura_sigilosa.png",
    "curacion_(1).png",
    "curacion_(2).png",
    "dos_ataques.png",
    "enfermedades.png",
    "entereza_(1).png",
    "entereza_(2).png",
    "fortuna_(1).png",
    "fortuna_(2).png",
    "fortuna_(3).png",
    "fortuna_(4).png",
    "fortuna_(5).png",
    "fortuna_(6).png",
    "fortuna_(7).png",
    "fortuna_(8).png",
    "gran_hechicero.png",
    "habil.png",
    "huida.png",
    "mejorar_guerrero.png",
    "miedo.png",
    "ocultos.png",
    "piel_dura.png",
    "precision.png",
    "rapido.png",
    "regeneracion.png",
    "regreso.png",
];

const poderCards_encounter = [
    "refuerzos_(1).png",
];

const poderCards_encounter_extra = [
    "refuerzos_(2).png",
];

const obstaculosCards_encounter = [
    "ladron.png",
    "emboscada_(1).png",
]

const obstaculosCards_encounter_extra = [
    "emboscada_(2).png",
]